// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CaptchaPartial = "_CaptchaPartial";
                public readonly string _Layout = "_Layout";
                public readonly string _SuccessPartial = "_SuccessPartial";
                public readonly string Error = "Error";
                public readonly string Lockout = "Lockout";
            }
            public readonly string _CaptchaPartial = "~/Views/Shared/_CaptchaPartial.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _SuccessPartial = "~/Views/Shared/_SuccessPartial.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Lockout = "~/Views/Shared/Lockout.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string Canonical = "Canonical";
                public readonly string CanonicalHelperModel = "CanonicalHelperModel";
                public readonly string Menu = "Menu";
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MetaRobots = "MetaRobots";
                public readonly string MetaRobotsHelperModel = "MetaRobotsHelperModel";
                public readonly string SiteMap = "SiteMap";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapList = "SiteMapList";
                public readonly string SiteMapNodel = "SiteMapNodel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapPath = "SiteMapPath";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapTitle = "SiteMapTitle";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Html = "Html";
                public readonly string Order = "Order";
                public readonly string Upload = "Upload";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
