// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GoldenCityShop.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Login()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ForgetPasswordCheckPhoneNumberExist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ForgetPasswordCheckPhoneNumberExist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckUserNameIsExist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckUserNameIsExist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckPhoneNumberIsExist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckPhoneNumberIsExist);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Login = "Login";
            public readonly string ForgetPasswordCheckPhoneNumberExist = "ForgetPasswordCheckPhoneNumberExist";
            public readonly string CheckUserNameIsExist = "CheckUserNameIsExist";
            public readonly string CheckPhoneNumberIsExist = "CheckPhoneNumberIsExist";
            public readonly string Register = "Register";
            public readonly string ForgetPassword = "ForgetPassword";
            public readonly string LogOut = "LogOut";
            public readonly string Account = "Account";
            public readonly string WishList = "WishList";
            public readonly string Orders = "Orders";
            public readonly string Comments = "Comments";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Login = "Login";
            public const string ForgetPasswordCheckPhoneNumberExist = "ForgetPasswordCheckPhoneNumberExist";
            public const string CheckUserNameIsExist = "CheckUserNameIsExist";
            public const string CheckPhoneNumberIsExist = "CheckPhoneNumberIsExist";
            public const string Register = "Register";
            public const string ForgetPassword = "ForgetPassword";
            public const string LogOut = "LogOut";
            public const string Account = "Account";
            public const string WishList = "WishList";
            public const string Orders = "Orders";
            public const string Comments = "Comments";
        }


        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ForgetPasswordCheckPhoneNumberExist s_params_ForgetPasswordCheckPhoneNumberExist = new ActionParamsClass_ForgetPasswordCheckPhoneNumberExist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ForgetPasswordCheckPhoneNumberExist ForgetPasswordCheckPhoneNumberExistParams { get { return s_params_ForgetPasswordCheckPhoneNumberExist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ForgetPasswordCheckPhoneNumberExist
        {
            public readonly string phoneNumber = "phoneNumber";
        }
        static readonly ActionParamsClass_CheckUserNameIsExist s_params_CheckUserNameIsExist = new ActionParamsClass_CheckUserNameIsExist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckUserNameIsExist CheckUserNameIsExistParams { get { return s_params_CheckUserNameIsExist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckUserNameIsExist
        {
            public readonly string userName = "userName";
        }
        static readonly ActionParamsClass_CheckPhoneNumberIsExist s_params_CheckPhoneNumberIsExist = new ActionParamsClass_CheckPhoneNumberIsExist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckPhoneNumberIsExist CheckPhoneNumberIsExistParams { get { return s_params_CheckPhoneNumberIsExist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckPhoneNumberIsExist
        {
            public readonly string phoneNumber = "phoneNumber";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ForgetPassword s_params_ForgetPassword = new ActionParamsClass_ForgetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ForgetPassword ForgetPasswordParams { get { return s_params_ForgetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ForgetPassword
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_WishList s_params_WishList = new ActionParamsClass_WishList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WishList WishListParams { get { return s_params_WishList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WishList
        {
            public readonly string page = "page";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ForgetPasswordPartial = "_ForgetPasswordPartial";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _RegisterPartial = "_RegisterPartial";
                public readonly string _SidbarMenuPartial = "_SidbarMenuPartial";
                public readonly string Account = "Account";
                public readonly string Comments = "Comments";
                public readonly string Login = "Login";
                public readonly string Orders = "Orders";
                public readonly string WishList = "WishList";
            }
            public readonly string _ForgetPasswordPartial = "~/Views/User/_ForgetPasswordPartial.cshtml";
            public readonly string _LoginPartial = "~/Views/User/_LoginPartial.cshtml";
            public readonly string _RegisterPartial = "~/Views/User/_RegisterPartial.cshtml";
            public readonly string _SidbarMenuPartial = "~/Views/User/_SidbarMenuPartial.cshtml";
            public readonly string Account = "~/Views/User/Account.cshtml";
            public readonly string Comments = "~/Views/User/Comments.cshtml";
            public readonly string Login = "~/Views/User/Login.cshtml";
            public readonly string Orders = "~/Views/User/Orders.cshtml";
            public readonly string WishList = "~/Views/User/WishList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserController : GoldenCityShop.Controllers.UserController
    {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModel.LoginViewModel viewModel, string returnUrl);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Login(ViewModel.LoginViewModel viewModel, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, viewModel, returnUrl);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ForgetPasswordCheckPhoneNumberExistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string phoneNumber);

        [NonAction]
        public override System.Web.Mvc.JsonResult ForgetPasswordCheckPhoneNumberExist(string phoneNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ForgetPasswordCheckPhoneNumberExist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "phoneNumber", phoneNumber);
            ForgetPasswordCheckPhoneNumberExistOverride(callInfo, phoneNumber);
            return callInfo;
        }

        [NonAction]
        partial void CheckUserNameIsExistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string userName);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckUserNameIsExist(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckUserNameIsExist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            CheckUserNameIsExistOverride(callInfo, userName);
            return callInfo;
        }

        [NonAction]
        partial void CheckPhoneNumberIsExistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string phoneNumber);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckPhoneNumberIsExist(string phoneNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckPhoneNumberIsExist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "phoneNumber", phoneNumber);
            CheckPhoneNumberIsExistOverride(callInfo, phoneNumber);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            RegisterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModel.RegisterViewModel viewModel);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Register(ViewModel.RegisterViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RegisterOverride(callInfo, viewModel);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ForgetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ForgetPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgetPassword);
            ForgetPasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ForgetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModel.ForgetPasswordViewModel viewModel);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ForgetPassword(ViewModel.ForgetPasswordViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ForgetPasswordOverride(callInfo, viewModel);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void LogOutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOut()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOut);
            LogOutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AccountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Account()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Account);
            AccountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void WishListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult WishList(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WishList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            WishListOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void OrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Orders()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Orders);
            OrdersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comments()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
            CommentsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
